apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: webshot
  name: webshot
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      name: webshot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: webshot
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - apps
      containers:
      - args:
        - start
        env:
        - name: PORT
          value: "5000"
        - name: NODE_ENV
          value: staging
        - name: NODE_PATH
          value: app/src
        - name: LOCAL_URL
          value: http://webshot.default.svc.cluster.local:5000
        - name: WIDGET_RENDER_URL
          value: https://staging.resourcewatch.org/webshot/
        - name: CT_URL
          valueFrom:
            secretKeyRef:
              key: CT_URL
              name: mssecrets
        - name: CT_TOKEN
          valueFrom:
            secretKeyRef:
              key: CT_TOKEN
              name: mssecrets
        - name: CT_REGISTER_MODE
          valueFrom:
            secretKeyRef:
              key: CT_REGISTER_MODE
              name: mssecrets
        - name: API_VERSION
          valueFrom:
            secretKeyRef:
              key: API_VERSION
              name: mssecrets
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: S3_ACCESS_KEY_ID
              name: mssecrets
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: S3_SECRET_ACCESS_KEY
              name: mssecrets
        image: vizzuality/webshot
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        name: webshot
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 512M
          requests:
            cpu: 250m
            memory: 256M
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
