language: node_js
node_js:
  - "12"
cache:
  directories:
  - "node_modules"
env:
  global:
    - CC_TEST_REPORTER_ID=a7e319ef5badf1c14191fc01c0342bdce0d4f7d794fd62ca8ffa3e3d522a9946
    - NODE_ENV=test
    - PORT=5037
    - API_VERSION=v1
    - LOCAL_URL=http://127.0.0.1:5037
    - CT_REGISTER_MODE=auto
    - CT_URL=http://127.0.0.1:9000
    - MONGO_PORT_27017_TCP_ADDR=127.0.0.1
    - S3_ACCESS_KEY_ID=1
    - S3_SECRET_ACCESS_KEY=1

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn test
  - yarn run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
