develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35739:35729"
  privileged: true
  environment:
    CT_REGISTER_MODE: auto
    CT_URL: http://mymachine:9000
    LOCAL_URL: http://mymachine:5000
    CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
    API_VERSION: v1
    S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
    S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
    FASTLY_ENABLED: "false"
  command: develop
  volumes:
    - ./app:/home/webshot-service/app
