test:
  extends:
    file: base.yml
    service: base
  container_name: webshot-service-test
  environment:
    NODE_ENV: test
    CT_URL: http://mymachine:9000
    CT_REGISTER_MODE: auto
    API_VERSION: v1
    S3_ACCESS_KEY_ID: 1
    S3_SECRET_ACCESS_KEY: 1
  command: test
