apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}
  name: {name}
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: {name}
    spec:
      containers:
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        args:
          - start
        env:
          - name: PORT
            value: "5000"
          - name: NODE_ENV
            value: staging
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://{name}.default.svc.cluster.local:5000
          - name: WIDGET_RENDER_URL
            value: https://staging.resourcewatch.org/webshot/
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: S3_ACCESS_KEY_ID
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: S3_ACCESS_KEY_ID
          - name: S3_SECRET_ACCESS_KEY
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: S3_SECRET_ACCESS_KEY

        ports:
          - containerPort: 5000
        securityContext:
          privileged: true

      restartPolicy: Always
