apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webshot
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: webshot
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
